source "https://rubygems.org"

gem "bigdecimal", "~> 3.3"
gem "jekyll", "~> 4.4"
gem "faraday-retry", "~> 2.3"
gem "minimal-mistakes-jekyll", "~> 4.28"
gem "jekyll-sass-converter", "~> 2.2"
gem "jekyll-feed", "~> 0.17"
gem "jekyll-include-cache", "~> 0.2"
gem "jekyll-paginate-v2", "~> 3.0"
gem "jekyll-sitemap", "~> 1.0"
gem "kramdown-parser-gfm", "~> 1.1"
